const {chromium}=require('playwright-core'),{spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),JSZip=require('jszip');
(async()=>{const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5195'],{stdio:'ignore'});let browser,passed=0;const ok=m=>{passed++;console.log('PASS '+m)};try{
 for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:5195');break}catch{await new Promise(r=>setTimeout(r,120))}}
 browser=await chromium.launch({headless:true,executablePath:process.env.WORDMD_BROWSER||'/tmp/termd-chromium',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const page=await browser.newPage({viewport:{width:1400,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.showOpenFilePicker=undefined;window.showSaveFilePicker=undefined});await page.goto('http://127.0.0.1:5195');const bytes=await fs.readFile('tests/assets/resize.png'),base64=bytes.toString('base64');const app=()=>page.locator('.app[data-active-document="true"]:visible'),mode=async name=>{await app().locator('.status-modes').getByRole('button',{name,exact:true}).click();await page.waitForTimeout(60)},image=()=>app().locator('.image-node img').last();
 const open=async(buffer,name)=>{const input=await app().count()?app().locator('input[type=file]').first():page.locator('.empty-workspace input[type=file]');await input.setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(buffer)});await page.getByRole('tab',{name,selected:true,exact:true}).waitFor();await page.waitForTimeout(80)};
 const paste=async(type='image/png',html='<img src="file:///clipboard/screenshot.png">')=>{await app().locator('.ProseMirror').click();await page.keyboard.press('Control+End');await page.evaluate(({base64,type,html})=>{const data=new DataTransfer();data.items.add(new File([Uint8Array.from(atob(base64),c=>c.charCodeAt(0))],'Screenshot.png',{type}));data.setData('text/html',html);document.querySelector('.app[data-active-document="true"] .ProseMirror').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))},{base64,type,html});await page.waitForTimeout(150)};
 const save=async()=>{const event=page.waitForEvent('download');await page.keyboard.press('Control+s');return fs.readFile(await(await event).path())};
 await open('# Clipboard\n\nBefore paste.\n','clipboard.md');await paste();await image().waitFor();assert.equal(await image().evaluate(el=>el.complete&&el.naturalWidth>0),true);assert.match(await image().getAttribute('src'),/^data:image\/png;base64,/);assert.equal(await app().locator('.image-placeholder').count(),0);ok('A screenshot file takes priority over its inaccessible clipboard HTML path and displays immediately');
 await image().click();assert.equal(await app().locator('.image-resize-handle').count(),8);await page.keyboard.press('Control+z');assert.equal(await app().locator('.image-node img').count(),0);await page.keyboard.press('Control+Shift+z');await image().waitFor();ok('Pasted screenshots use the resize controls and shared undo/redo');
 const md=await save();assert.match(md.toString(),/data:image\/png;base64,/);await open(md,'reopened.md');assert.equal(await image().evaluate(el=>el.complete&&el.naturalWidth>0),true);ok('Markdown saving and reopening retains the screenshot without another file or network request');
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('wordmd-settings')||'{}');s.remoteImages=false;localStorage.setItem('wordmd-settings',JSON.stringify(s))});
 const exported=await page.evaluate(async()=>{const [{exportDocument},{defaultSettings}]=await Promise.all([import('/src/document-export.ts'),import('/src/core.ts')]);const source=document.querySelector('.app[data-active-document="true"] .image-node img').getAttribute('src');const doc={documentId:crypto.randomUUID(),fileName:'embedded.md',format:'md',source:'![Capture]('+source+')',comments:[],bom:false};const result=await exportDocument('docx',doc,new Map(),{...defaultSettings,remoteImages:false});return {bytes:Array.from(new Uint8Array(await result.blob.arrayBuffer())),warnings:result.warnings}});assert.deepEqual(exported.warnings,[]);const word=await JSZip.loadAsync(Buffer.from(exported.bytes));assert.equal(Object.keys(word.files).filter(n=>n.startsWith('word/media/')&&!word.files[n].dir).length,1);ok('Embedded screenshots also export to Word while external images are disabled');
 await page.getByRole('button',{name:'New document',exact:true}).click();await page.getByRole('menuitem',{name:'Commented Markdown (.trmd)',exact:true}).click();await page.waitForTimeout(80);await paste();assert.match(await image().getAttribute('src'),/^blob:/);const native=await save(),archive=await JSZip.loadAsync(native),manifest=JSON.parse(await archive.file('manifest.json').async('string'));assert.equal(manifest.resources.length,1);assert.deepEqual(Buffer.from(await archive.file(manifest.resources[0]).async('uint8array')),bytes);await page.locator('.document-tab.active .tab-close').click();await open(native,'screenshot.trmd');assert.equal(await image().evaluate(el=>el.complete&&el.naturalWidth>0),true);ok('TRMD stores the original screenshot bytes as an asset and reopens them correctly');
 await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText('\n\nAfter capture.\n');await mode('Split');await paste();assert.equal(await app().locator('.image-node img').count(),2);assert.match(await app().locator('.cm-content').innerText(),/assets\/pasted-/);ok('Pasting into the visual pane in Split synchronizes the Markdown code');
 await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText('\n\nMore text.\n');await mode('Visual');await app().locator('.ProseMirror').click();await page.keyboard.press('Control+End');await app().locator('.tabs').getByRole('button',{name:'Home',exact:true}).click();await page.evaluate(base64=>{Object.defineProperty(navigator.clipboard,'read',{configurable:true,value:async()=>[{types:['image/png'],getType:async()=>new Blob([Uint8Array.from(atob(base64),c=>c.charCodeAt(0))],{type:'image/png'})}]})},base64);await app().locator('.ribbon').getByRole('button',{name:'Paste',exact:true}).click();await page.waitForTimeout(150);assert.equal(await app().locator('.image-node img').count(),3);ok('The ribbon Paste action supports image-only clipboard items');
 const count=await app().locator('.image-node img').count();await paste('image/svg+xml','');assert.equal(await app().locator('.image-node img').count(),count);assert.ok(await page.getByRole('status').filter({hasText:'Use PNG'}).isVisible());ok('Unsupported image formats are rejected without inserting broken image nodes');
 const safe=await page.evaluate(async()=>{const {safeURL}=await import('/src/core.ts');return [safeURL('data:image/svg+xml;base64,PHN2Zz4=',true),safeURL('data:text/html;base64,SGVsbG8=',true),safeURL('data:image/png;base64,AAAA'),safeURL('data:image/png;base64,AAAA',true)]});assert.deepEqual(safe,[false,false,false,true]);ok('Raster data URLs are allowed only for images; SVG and executable data remain blocked');assert.deepEqual(errors,[]);ok('No uncaught browser exceptions');console.log(JSON.stringify({passed,errors}));
 }finally{if(browser)await browser.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
