const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const fs = require('node:fs/promises'), path = require('node:path'), assert = require('node:assert/strict'), { spawn } = require('node:child_process'), JSZip = require('jszip');
(async()=>{const server=spawn(process.execPath,['launch.cjs','--no-browser'],{stdio:'ignore'});let browser;try{
 for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:43821/');break}catch{await new Promise(r=>setTimeout(r,120))}}
 browser=await chromium.launch({headless:true,args:packed.args,executablePath:process.env.WORDMD_BROWSER||path.resolve('../qa-browser/chromium')});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const nativeLocator=page.locator.bind(page);page.locator=(selector,...args)=>nativeLocator('.app[data-active-document="true"] '+selector,...args);page.on('dialog',d=>d.accept());await page.addInitScript(() => { window.showSaveFilePicker = undefined; });await page.goto('http://127.0.0.1:43821/');await page.locator('.ProseMirror').waitFor();
 const open=async(source)=>{await page.locator('input[type=file]').first().setInputFiles({name:'extra.md',mimeType:'text/markdown',buffer:Buffer.from(source)});await page.waitForTimeout(150)};
 const select=async(text)=>{await page.locator('.ProseMirror').evaluate((el,text)=>{el.focus();const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){let i=n.textContent.indexOf(text);if(i>=0){const r=document.createRange();r.setStart(n,i);r.setEnd(n,i+text.length);getSelection().removeAllRanges();getSelection().addRange(r);return}}throw Error(text)},text);await page.waitForTimeout(100)};
 const tab=async name=>page.locator('.tabs').getByRole('button',{name,exact:true}).click();
 const md=async()=>{await tab('Archivo');let p=page.waitForEvent('download');await page.locator('.ribbon').getByRole('button',{name: await page.getByRole('tab',{selected:true}).getAttribute('aria-label').then(n=>n.endsWith('.trmd')?'Guardar .md…':'Guardar'),exact:true}).click();let d=await p;return (await fs.readFile(await d.path())).toString()};
 const zip=async()=>{await tab('Archivo');let p=page.waitForEvent('download');await page.locator('.ribbon').getByRole('button',{name: (await page.getByRole('tab',{selected:true}).getAttribute('aria-label')).endsWith('.trmd')?'Guardar':'Guardar como .trmd…',exact:true}).click();let d=await p;return JSZip.loadAsync(await fs.readFile(await d.path()))};
 let passed=0;const ok=n=>{passed++;console.log('PASS '+n)};
 await open('Plain text\n');await page.locator('.ProseMirror').click();await page.keyboard.press('Control+End');
 await page.locator('.ProseMirror').evaluate(el=>{const data=new DataTransfer();data.setData('text/html','<h2>Office heading</h2><p><strong>Bold paste</strong> and <em>italic paste</em></p>');data.setData('text/plain','Office heading\nBold paste and italic paste');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))});
 let source=await md();assert.ok(source.includes('## Office heading'));assert.ok(source.includes('**Bold paste**'));assert.ok(source.includes('*italic paste*'));ok('HTML paste converts supported headings and emphasis');
 const beforeMerged=source;await page.locator('.ProseMirror').evaluate(el=>{el.focus();const data=new DataTransfer();data.setData('text/html','<table><tr><td colspan="10">Merged</td></tr></table>');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))});assert.equal(await md(),beforeMerged);ok('Merged tables are rejected with a conversion notice');
 await open('Cut me safely\n');await tab('Inicio');await select('Cut me');await page.evaluate(()=>{window.oldClipboard=navigator.clipboard;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write:()=>Promise.reject(Error('denied')),writeText:()=>Promise.reject(Error('denied'))}})});await page.locator('.ribbon').getByRole('button',{name:'Cortar',exact:true}).click();assert.equal(await md(),'Cut me safely\n');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:window.oldClipboard}));ok('Failed clipboard copy never deletes cut text');
 await open('# Images\n\nEnd.\n');await tab('Insertar');await page.locator('.ProseMirror p').click();await page.keyboard.press('End');await page.getByRole('button',{name:'Imagen',exact:true}).click();await page.locator('.modal input').first().fill('Blue pixel');const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');await page.locator('input[type=file]').nth(1).setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:png});await page.locator('.modal-actions .primary-button').click();let archive=await zip();assert.ok(archive.file('assets/pixel.png'));assert.ok((await archive.file('document.md').async('string')).includes('![Blue pixel](assets/pixel.png)'));ok('Authorized local images are bundled with Markdown');
 const manifest=JSON.parse(await archive.file('manifest.json').async('string'));manifest.documentId='e679df30-5791-4de1-b0d3-708f77000001';archive.file('manifest.json',JSON.stringify(manifest));const nativeComments=JSON.parse(await archive.file('comments.json').async('string'));nativeComments.documentId=manifest.documentId;archive.file('comments.json',JSON.stringify(nativeComments));let packageBuffer=await archive.generateAsync({type:'nodebuffer'});await page.locator('input[type=file]').first().setInputFiles({name:'reopen.trmd',mimeType:'application/x-termd',buffer:packageBuffer});await page.waitForTimeout(180);assert.ok(await page.locator('.image-node img').isVisible());await page.locator('.status-modes').getByRole('button',{name:'Lectura',exact:true}).click();assert.ok(await page.locator('.reading img').isVisible());ok('TRMD resources render in both visual and reading views');
 await page.locator('.status-modes').getByRole('button',{name:'Visual',exact:true}).click();await open('Save original\n');await page.evaluate(()=>{window.mockBytes=new TextEncoder().encode('existing file');window.mockWrites=0;const handle={name:'extra.md',getFile:async()=>new File([window.mockBytes],'extra.md'),createWritable:async()=>({write:async bytes=>{window.pendingBytes=bytes},close:async()=>{window.mockBytes=window.pendingBytes;window.mockWrites++}})};window.showSaveFilePicker=async()=>handle});await tab('Archivo');await page.locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click();await page.waitForFunction(()=>window.mockWrites===1);assert.equal(await page.evaluate(()=>window.mockWrites),1);
 await page.evaluate(()=>window.mockBytes=new TextEncoder().encode('External change\n'));await page.locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('heading',{name:'El archivo ha cambiado fuera de Termd.',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.mockWrites),1);await page.locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();ok('Simulated file adapter detects an external change before writing');
 await page.evaluate(()=>{window.showSaveFilePicker=undefined});await open('# A review\n\nA clear statement.\n');await tab('Inicio');await select('clear statement');await page.keyboard.press('Control+Alt+m');const convertWait=page.waitForEvent('download');await page.locator('.modal').getByRole('button',{name:'Guardar como .trmd…',exact:true}).click();await convertWait;await page.locator('#new-comment-text').fill('This claim needs a source.');await page.locator('.new-card .primary-button').click();await page.screenshot({path:'../outputs/wordmd-qa/comments.png'});
 assert.deepEqual(errors,[]);ok('Production bundle, CSP and comment layout have no browser exceptions');
 const traversal=await fetch('http://127.0.0.1:43821/%2e%2e%2fpackage.json');assert.notEqual(traversal.status,200);const host=await new Promise((resolve,reject)=>require('node:http').get('http://127.0.0.1:43821/',{headers:{Host:'malicious.example'}},res=>{res.resume();resolve(res.statusCode)}).on('error',reject));assert.equal(host,403);ok('Local server denies other hosts and file traversal');
 const standalone=await browser.newPage();const offlineRequests=[];standalone.on('request',r=>{if(/^https?:/.test(r.url()))offlineRequests.push(r.url())});await standalone.goto('file://'+path.resolve('Termd.html'));await standalone.locator('.ProseMirror h1').waitFor();assert.equal(offlineRequests.length,0);await standalone.getByRole('button',{name:'Configuración',exact:true}).click();await standalone.getByRole('heading',{name:'Configuración',exact:true}).waitFor();await standalone.locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();await standalone.screenshot({path:'../outputs/wordmd-qa/standalone.png'});ok('Self-contained HTML opens and works without network requests');
 console.log(JSON.stringify({passed,errors},null,2));
 }finally{if(browser)await browser.close();server.kill()}})().catch(e=>{console.error(e);process.exit(1)});
