const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const fs = require('node:fs/promises'), path = require('node:path'), assert = require('node:assert/strict'), { spawn } = require('node:child_process'), JSZip = require('jszip');
(async () => {
 const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5186'], { stdio:'ignore' }); let browser;
 try {
  for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:5186/');break}catch{await new Promise(r=>setTimeout(r,120))}}
  browser = await chromium.launch({headless:true,args:packed.args,executablePath:(process.env.TERMD_BROWSER||process.env.WORDMD_BROWSER)||path.resolve('../qa-browser/chromium')});
  const context = await browser.newContext({viewport:{width:1512,height:1000}}), page = await context.newPage(), errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept()); await page.addInitScript(()=>{window.showSaveFilePicker=undefined;window.showOpenFilePicker=undefined});
  await page.addInitScript(() => { const saved = JSON.parse(localStorage.getItem('wordmd.settings') || '{}'); localStorage.setItem('wordmd.settings', JSON.stringify({...saved, lang: 'es'})); });await page.goto('http://127.0.0.1:5186/');await page.getByRole('link',{name:/^(Welcome document|Documento de Bienvenida)$/}).click(); const app=()=>page.locator('.app[data-active-document="true"]:visible'), active=()=>page.getByRole('tab',{selected:true});
  let passed=0; const ok=n=>{passed++;console.log('PASS '+n)};
  const file=async()=>app().locator('.tabs').getByRole('button',{name:'Archivo',exact:true}).click();
  const readDownload=async(action)=>{const wait=page.waitForEvent('download');await action();const d=await wait;return {name:d.suggestedFilename(),bytes:await fs.readFile(await d.path())}};
  const create=async(format)=>{await file();await app().getByRole('button',{name:'Nuevo',exact:true}).click();const menu=page.getByRole('menu',{name:'Tipo de documento'});assert.ok(await menu.isVisible());const item=menu.getByRole('menuitem',{name:format==='md'?'Markdown (.md)':'Markdown comentado (.trmd)',exact:true});const box=await item.boundingBox();assert.ok(box.y>90 && box.height>20);await item.click();};
  const open=async(bytes,name)=>{await app().locator('input[type=file]').first().setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(bytes)});};
  const select=async(text)=>{await app().locator('.ProseMirror').evaluate((el,text)=>{el.focus();const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const i=n.textContent.indexOf(text);if(i>=0){const r=document.createRange();r.setStart(n,i);r.setEnd(n,i+text.length);getSelection().removeAllRanges();getSelection().addRange(r);return}}throw Error(text)},text);await page.waitForTimeout(70)};
  const cleanTabs=async()=>{while(await page.getByRole('tab').count()){await page.locator('.tab-close').last().click();if(await page.locator('.close-document-modal').isVisible())await page.getByRole('button',{name:'Cerrar sin guardar',exact:true}).click();}};
  await create('md');assert.match(await active().getAttribute('aria-label'),/\.md$/);assert.equal(await active().locator('[data-document-icon=md]').count(),1);ok('File → New exposes two usable format choices; Markdown keeps the folded-page icon');
  await create('trmd');assert.match(await active().getAttribute('aria-label'),/\.trmd$/);assert.equal(await active().locator('[data-document-icon=trmd]').count(),1);await file();assert.ok(await app().getByRole('button',{name:'Guardar .md…',exact:true}).isVisible());assert.equal(await app().getByRole('button',{name:/Exportar paquete|Abrir comentarios|Guardar comentarios/}).count(),0);await page.screenshot({path:'../outputs/termd-formats.png'});ok('TRMD has its own rounded-page icon and simplified File ribbon');
  let emptyNative=await readDownload(()=>app().locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click());assert.match(emptyNative.name,/\.trmd$/);let archive=await JSZip.loadAsync(emptyNative.bytes);assert.equal(await archive.file('document.md').async('string'),'');assert.equal(JSON.parse(await archive.file('manifest.json').async('string')).formatVersion,1);ok('Empty TRMD saves as a valid native file with no automatic conversion');
  await cleanTabs();await page.getByRole('heading',{name:'No hay ningún documento activo',exact:true}).waitFor();await page.getByRole('button',{name:'Nuevo documento',exact:true}).first().click();await page.getByRole('menuitem',{name:'Markdown comentado (.trmd)',exact:true}).click();assert.match(await active().getAttribute('aria-label'),/\.trmd$/);await cleanTabs();await page.getByRole('button',{name:'Nuevo documento',exact:true}).first().click();await page.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).click();assert.match(await active().getAttribute('aria-label'),/\.md$/);ok('Empty workspace offers both formats without creating documents automatically');
  await page.getByRole('button',{name:'Nuevo documento',exact:true}).first().click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.match(await active().getAttribute('aria-label'),/\.trmd$/);ok('The top + menu supports keyboard format selection');
  const original='\uFEFF# Documento\r\n\r\nUn fragmento revisable.\r\n';await open(Buffer.from(original),'original.md');await active().filter({hasText:'original.md'}).waitFor();await file();assert.ok(await app().getByRole('button',{name:'Guardar como .trmd…',exact:true}).isVisible());const md=await readDownload(()=>app().locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click());assert.equal(md.name,'original.md');assert.deepEqual(md.bytes,Buffer.from(original));ok('Saving opened Markdown preserves its extension and exact BOM/CRLF bytes');
  await select('fragmento revisable');await page.keyboard.press('Control+Alt+m');await page.getByRole('heading',{name:'Convertir a documento con comentarios',exact:true}).waitFor();await app().locator('.modal').getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await app().locator('#new-comment-text').count(),0);assert.equal(await active().getAttribute('aria-label'),'original.md');ok('Cancelling comment conversion leaves Markdown unchanged and creates no comment');
  // Browser file adapter exercises authorized in-place writes, save-as, cancellation and errors.
  await page.evaluate(original=>{
   window.mockFiles={'original.md':new TextEncoder().encode(original)},window.mockWrites=[],window.mockPickerCalls=[],window.mockOpen=['original.md'];
   window.makeHandle=name=>({name,getFile:async()=>new File([window.mockFiles[name]],name),createWritable:async()=>{let bytes;return {write:async data=>{if(window.failWrite)throw Error('write failed');bytes=new Uint8Array(data)},close:async()=>{window.mockFiles[name]=bytes;window.mockWrites.push(name)},abort:async()=>{}}}});
   window.showOpenFilePicker=async()=>window.mockOpen.map(window.makeHandle);
   window.showSaveFilePicker=async options=>{window.mockPickerCalls.push(options);if(window.abortPicker){window.abortPicker=false;throw new DOMException('Cancelled','AbortError')}return window.makeHandle(window.nextName||options.suggestedName)};
  },original);
  // Open with a handle, since the input fallback deliberately has no write permission.
  await file();await app().getByRole('button',{name:'Abrir',exact:true}).click();await page.waitForTimeout(80);
  await app().locator('.status-modes').getByRole('button',{name:'Código',exact:true}).click();await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText('Edición.');await file();await app().locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click();await page.waitForFunction(()=>window.mockWrites.length===1);assert.equal(await page.evaluate(()=>window.mockPickerCalls.length),0);assert.match(await page.evaluate(()=>new TextDecoder().decode(window.mockFiles['original.md'])),/Edición\.$/);ok('Opened MD writes back to its authorized MD file without conversion or a new picker');
  await app().locator('.status-modes').getByRole('button',{name:'Visual',exact:true}).click();await select('fragmento revisable');await page.keyboard.press('Control+Alt+m');
  const mdBefore=await page.evaluate(()=>Array.from(window.mockFiles['original.md']));await app().locator('.modal').getByRole('button',{name:'Convertir a .trmd',exact:true}).click();await app().locator('#new-comment-text').waitFor();assert.equal(await active().getAttribute('aria-label'),'original.trmd');assert.equal(await active().locator('.tab-dirty').count(),1);assert.equal(await page.evaluate(()=>window.mockPickerCalls.length),0);assert.equal(await page.evaluate(()=>window.mockWrites.length),1);assert.deepEqual(await page.evaluate(()=>Array.from(window.mockFiles['original.md'])),mdBefore);ok('First comment converts in memory, marks unsaved and neither opens a picker nor writes the original MD');
  await app().locator('#new-comment-text').fill('Comentario conservado');await page.evaluate(()=>window.abortPicker=true);await page.keyboard.press('Control+s');await page.waitForTimeout(100);assert.equal(await active().getAttribute('aria-label'),'original.trmd');assert.equal(await active().locator('.tab-dirty').count(),1);assert.equal(await page.evaluate(()=>window.mockWrites.length),1);assert.equal(await app().locator('.comment-body').textContent(),'Comentario conservado');ok('Cancelling the later save keeps converted content and comments unsaved');
  await page.evaluate(()=>window.failWrite=true);await page.keyboard.press('Control+s');await page.getByRole('status').filter({hasText:'No se pudo guardar'}).waitFor();assert.equal(await active().getAttribute('aria-label'),'original.trmd');assert.equal(await active().locator('.tab-dirty').count(),1);assert.deepEqual(await page.evaluate(()=>Array.from(window.mockFiles['original.md'])),mdBefore);await page.evaluate(()=>window.failWrite=false);ok('Failed TRMD writes keep changes and the original Markdown intact');
  await page.keyboard.press('Control+s');await page.waitForFunction(()=>window.mockWrites.at(-1)==='original.trmd'&&window.mockWrites.length===2);archive=await JSZip.loadAsync(Buffer.from(await page.evaluate(()=>Array.from(window.mockFiles['original.trmd']))));let data=JSON.parse(await archive.file('comments.json').async('string'));assert.equal(data.comments[0].body,'Comentario conservado');assert.equal(data.comments[0].anchor.quote,'fragmento revisable');assert.deepEqual(await page.evaluate(()=>Array.from(window.mockFiles['original.md'])),mdBefore);ok('Saving later asks for a native destination and preserves the comment and original MD');
  await app().locator('.status-modes').getByRole('button',{name:'Código',exact:true}).click();await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Pendiente');await file();await app().getByRole('button',{name:'Guardar .md…',exact:true}).click();await page.waitForFunction(()=>window.mockWrites.at(-1)==='original.md'&&window.mockWrites.length===3);assert.equal(await active().getAttribute('aria-label'),'original.trmd');assert.equal(await active().locator('.tab-dirty').count(),1);assert.ok(await app().locator('.comment-body').isVisible());assert.match(await page.evaluate(()=>new TextDecoder().decode(window.mockFiles['original.md'])),/Pendiente$/);ok('Save MD exports a text copy, keeps TRMD and comments active, and does not mark native changes saved');
  await app().locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click();await page.waitForFunction(()=>window.mockWrites.length===4);await active().locator('.tab-dirty').waitFor({state:'detached'});await page.getByRole('button',{name:'Cerrar original.trmd',exact:true}).click();assert.equal(await page.locator('.close-document-modal').count(),0);await page.evaluate(()=>window.mockOpen=['original.trmd']);await file();await app().getByRole('button',{name:'Abrir',exact:true}).click();await page.getByRole('tab',{name:'original.trmd',exact:true}).waitFor();assert.equal(await app().locator('.comment-body').textContent(),'Comentario conservado');ok('Native TRMD reopens with comments and its authorized write handle; saved tabs close without a warning');
  const writes=await page.evaluate(()=>window.mockWrites.length);await page.evaluate(()=>window.nextName='otra.trmd');await file();await app().getByRole('button',{name:'Guardar como',exact:true}).click();await page.waitForFunction(n=>window.mockWrites.length===n+1,writes);assert.equal(await active().getAttribute('aria-label'),'otra.trmd');assert.ok(await page.evaluate(()=>!!window.mockFiles['original.trmd']));await page.evaluate(()=>window.nextName=null);ok('TRMD Save as retains native format and comments while leaving the original file intact');
  await app().locator('.comment-footer').getByRole('button',{name:'Responder',exact:true}).click();await app().locator('.reply-form textarea').fill('Respuesta pendiente');await page.getByRole('button',{name:'Cerrar otra.trmd',exact:true}).click();await page.getByRole('button',{name:'Guardar y cerrar',exact:true}).click();await page.getByRole('tab',{name:'otra.trmd',exact:true}).waitFor({state:'detached'});archive=await JSZip.loadAsync(Buffer.from(await page.evaluate(()=>Array.from(window.mockFiles['otra.trmd']))));data=JSON.parse(await archive.file('comments.json').async('string'));assert.equal(data.comments[0].replies[0].body,'Respuesta pendiente');ok('Save and close includes pending replies in the same native file');
  await page.evaluate(()=>{window.mockOpen=['otra.trmd']});await file();await app().getByRole('button',{name:'Abrir',exact:true}).click();await app().locator('.comment-body').waitFor();await app().locator('.card-author').getByRole('button',{name:'Resolver',exact:true}).click();await app().locator('.comment-filter').selectOption('resolved');await page.evaluate(()=>{const bytes=window.mockFiles['otra.trmd'].slice();bytes[bytes.length-1]^=1;window.mockFiles['otra.trmd']=bytes});await file();await app().locator('.ribbon').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('heading',{name:'El archivo ha cambiado fuera de Termd.',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.mockWrites.length),writes+2);await app().locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();ok('Native conflict detection covers the entire TRMD container, including changes outside Markdown');
  // Format readers reject old ZIP packages, disguised legacy archives and invalid versions.
  await page.evaluate(()=>{window.showSaveFilePicker=undefined;window.showOpenFilePicker=undefined});const count=await page.getByRole('tab').count();await open(emptyNative.bytes,'old.zip');await page.getByRole('status').filter({hasText:'paquetes ZIP'}).waitFor();assert.equal(await page.getByRole('tab').count(),count);ok('ZIP extensions are rejected even if their contents resemble a native document');
  const legacy=new JSZip();legacy.file('wordmd.manifest.json',JSON.stringify({app:'WordMD',version:1,document:'a.md',resources:[]}));legacy.file('a.md','Legacy');await open(await legacy.generateAsync({type:'nodebuffer'}),'legacy.trmd');await page.getByRole('status').filter({hasText:'inválido'}).waitFor();assert.equal(await page.getByRole('tab').count(),count);ok('Renaming an old ZIP package to TRMD does not bypass format validation');
  archive=await JSZip.loadAsync(emptyNative.bytes);const manifest=JSON.parse(await archive.file('manifest.json').async('string'));manifest.formatVersion=999;archive.file('manifest.json',JSON.stringify(manifest));await open(await archive.generateAsync({type:'nodebuffer'}),'future.trmd');await page.getByRole('status').filter({hasText:'inválido'}).waitFor();assert.equal(await page.getByRole('tab').count(),count);ok('Unsupported native format versions are rejected without adding a tab');
  // Codec-level fixture also checks resources and stable anchors over byte-preserving round trips.
  const codec=await page.evaluate(async()=>{const f=await import('/src/files.ts'),c=await import('/src/core.ts');const source='# Revisión\r\n\r\nTexto 😀 con café.\r\n';const doc={documentId:crypto.randomUUID(),fileName:'prueba.trmd',format:'trmd',source,bom:true,comments:[{id:crypto.randomUUID(),body:'Nota',authorLabel:'A',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'resolved',anchor:c.anchorFor(source,15,20),replies:[]}]};const bytes=await f.encodeTRMD(doc,new Map([['assets/test.png',new Blob([new Uint8Array([1,2,3])],{type:'image/png'})]]));const read=await f.importTRMD(new File([bytes],'prueba.trmd'));return {source:read.doc.source,bom:read.doc.bom,comments:read.doc.comments,resources:Array.from(new Uint8Array(await read.resources.get('assets/test.png').arrayBuffer()))}});assert.equal(codec.source,'# Revisión\r\n\r\nTexto 😀 con café.\r\n');assert.ok(codec.bom);assert.equal(codec.comments[0].status,'resolved');assert.deepEqual(codec.resources,[1,2,3]);ok('Native codec preserves BOM, CRLF, Unicode, comment metadata and image bytes');
  await create('trmd');const newNativeName=await active().getAttribute('aria-label');await app().locator('.ProseMirror').click();await page.keyboard.insertText('Anotación de prueba.');await select('Anotación');await page.keyboard.press('Control+Alt+m');await app().locator('#new-comment-text').fill('Nota temporal');await app().locator('.new-card .primary-button').click();await app().locator('.comment-footer').getByRole('button',{name:'Eliminar',exact:true}).click();assert.equal(await app().locator('.comment-body').count(),0);const withoutComments=await readDownload(()=>page.keyboard.press('Control+s'));assert.equal(withoutComments.name,newNativeName);archive=await JSZip.loadAsync(withoutComments.bytes);assert.equal(JSON.parse(await archive.file('comments.json').async('string')).comments.length,0);await page.keyboard.press('Control+z');assert.equal(await app().locator('.comment-body').textContent(),'Nota temporal');assert.equal(await active().getAttribute('aria-label'),newNativeName);ok('Deleting every comment and undoing keeps TRMD format and its icon');
  await page.keyboard.press('F2');await page.getByLabel('Nombre del documento').fill('nombre.md');await page.getByLabel('Nombre del documento').press('Enter');assert.equal(await active().getAttribute('aria-label'),'nombre.trmd');assert.equal(await active().locator('[data-document-icon=trmd]').count(),1);ok('Inline rename cannot silently change the native format through its extension');
  await create('md');const withAssetName=await active().getAttribute('aria-label');await app().locator('input[type=file]').nth(2).setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from([1,2,3])});await page.getByRole('button',{name:'Cerrar '+withAssetName,exact:true}).click();const withAsset=await readDownload(()=>page.getByRole('button',{name:'Guardar como .trmd y cerrar',exact:true}).click());await page.getByRole('tab',{name:withAssetName,exact:true}).waitFor({state:'detached'});archive=await JSZip.loadAsync(withAsset.bytes);assert.ok(archive.file('pixel.png'));assert.deepEqual(await archive.file('pixel.png').async('nodebuffer'),Buffer.from([1,2,3]));ok('Closing Markdown with unsaved local assets explicitly offers native saving and preserves their bytes');
  assert.deepEqual(errors,[]);ok('No uncaught browser errors in format and save flows');console.log(JSON.stringify({passed,errors},null,2));
 }finally{if(browser)await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exit(1)});
