const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const { spawn } = require('node:child_process'), assert = require('node:assert/strict'), fs = require('node:fs/promises'), path = require('node:path'), JSZip = require('jszip');
(async () => {
 const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', '5193'], { stdio: 'ignore' }); let browser, passed = 0;
 const ok = message => { passed++; console.log('PASS ' + message); };
 try {
  for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:5193');break}catch{await new Promise(r=>setTimeout(r,120))}}
  browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],executablePath:(process.env.TERMD_BROWSER||process.env.WORDMD_BROWSER)||await packed.executablePath()});
  const page=await browser.newPage({viewport:{width:1500,height:1000}}), errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(() => {
   window.__saveCalls=0;window.__openName='original.md';window.__saveName='copy.md';window.__permission='granted';window.__permissionCalls=0;window.__printCalls=0;window.print=()=>window.__printCalls++;
   window.__handle=async name=>{const root=await navigator.storage.getDirectory(),dir=await root.getDirectoryHandle('termd152-tests',{create:true});return dir.getFileHandle(name,{create:true})};
   window.__write=async(name,text)=>{const handle=await window.__handle(name),stream=await handle.createWritable();await stream.write(text);await stream.close()};
   window.showOpenFilePicker=async()=>{const handle=await window.__handle(window.__openName);if(window.__openName==='original.md'&&!(await handle.getFile()).size)await window.__write('original.md','# Original\n\nExact text.\n');handle.queryPermission=async()=>window.__permission;handle.requestPermission=async()=>{window.__permissionCalls++;return window.__permission};return [handle]};
   window.showSaveFilePicker=async options=>{window.__saveCalls++;const name=window.__saveName.endsWith('.trmd')?window.__saveName:options.suggestedName.endsWith('.trmd')?'native.trmd':window.__saveName;return window.__handle(name)};
  });
  await page.goto('http://127.0.0.1:5193');
  const support=page.locator('.support-link');assert.equal(await support.evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(36, 87, 197)');assert.equal(await support.evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');await support.hover();await page.waitForTimeout(220);assert.notEqual(await support.evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(36, 87, 197)');ok('Support Termd uses the logo blue, white heart/text and a visible hover transition');const app=()=>page.locator('.app[data-active-document="true"]:visible'),quick=()=>page.getByRole('toolbar',{name:'Quick access',exact:true}),mode=async name=>{await app().locator('.status-modes').getByRole('button',{name,exact:true}).click();await page.waitForTimeout(80)},file=async()=>app().locator('.tabs').getByRole('button',{name:'File',exact:true}).click();
  const idle=async()=>{await page.waitForTimeout(80);await page.waitForFunction(()=>!document.querySelector('.document-quick-actions button').disabled)};
  const save=async()=>{await quick().getByRole('button',{name:'Save',exact:true}).click();await idle()};
  const read=async name=>page.evaluate(async name=>await (await (await window.__handle(name)).getFile()).text(),name),calls=()=>page.evaluate(()=>window.__saveCalls);
  assert.equal(await quick().getByRole('button',{name:'Save',exact:true}).isDisabled(),true);assert.equal(await quick().getByRole('button',{name:'Undo',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.fullscreenElement),null);ok('Quick access precedes tabs, is disabled without a document and Escape does not enter fullscreen');
  await page.getByRole('button',{name:'Open document',exact:true}).click();await page.getByRole('tab',{name:'original.md',selected:true,exact:true}).waitFor();await page.waitForTimeout(100);await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText('Changed.');await save();assert.match(await read('original.md'),/Changed\.$/);assert.equal(await calls(),0);ok('Opening Markdown through the picker and saving overwrites that file without a save dialog');
  assert.equal(await quick().getByRole('button',{name:'Undo',exact:true}).isDisabled(),false);await quick().getByRole('button',{name:'Undo',exact:true}).click();assert.ok(!(await app().locator('.cm-content').innerText()).includes('Changed.'));await quick().getByRole('button',{name:'Redo',exact:true}).click();assert.match(await app().locator('.cm-content').innerText(),/Changed\./);ok('Quick access Undo and Redo operate on the active document history');
  await file();await app().locator('.ribbon').getByRole('button',{name:'Save as',exact:true}).click();await idle();assert.equal(await calls(),1);await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Copy edit.');await save();assert.equal(await calls(),1);assert.match(await read('copy.md'),/Copy edit\.$/);assert.ok(!(await read('original.md')).includes('Copy edit'));ok('Save as chooses a new destination once; subsequent saves update that copy');
  await page.getByRole('button',{name:'New document',exact:true}).click();await page.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).click();await save();assert.equal(await calls(),2);await save();assert.equal(await calls(),2);ok('A newly created document requests a destination only for its first save');
  await page.evaluate(()=>window.__openName='original.md');await file();await app().locator('.ribbon').getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('tab',{name:'original.md',selected:true,exact:true}).waitFor();await page.waitForTimeout(100);await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Denied edit.');const unchanged=await read('original.md');await page.evaluate(()=>window.__permission='denied');await save();assert.equal(await read('original.md'),unchanged);assert.equal(await calls(),2);assert.ok(await page.getByRole('status').filter({hasText:'Permission to modify'}).isVisible());await page.evaluate(()=>window.__permission='granted');await save();assert.match(await read('original.md'),/Denied edit\./);ok('Denied write permission preserves unsaved work and does not switch silently to Save as');
  await page.evaluate(async()=>{await window.__write('drop.md','# Dropped\n\nDrop text.\n');const handle=await window.__handle('drop.md'),file=await handle.getFile(),event=new Event('drop',{bubbles:true,cancelable:true});Object.defineProperty(event,'dataTransfer',{value:{types:['Files'],files:[file],items:[{kind:'file',getAsFile:()=>file,getAsFileSystemHandle:()=>Promise.resolve(handle)}]}});document.querySelector('.app[data-active-document="true"] .workarea').dispatchEvent(event)});
  await page.getByRole('tab',{name:'drop.md',exact:true}).waitFor();await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' After drop.');await save();assert.match(await read('drop.md'),/After drop\./);assert.equal(await calls(),2);ok('Drag and drop preserves a writable file handle and saves over the dropped file');
  await page.waitForTimeout(1100);assert.equal(await page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('wordmd',1);request.onsuccess=()=>{const db=request.result,query=db.transaction('drafts').objectStore('drafts').getAll();query.onsuccess=()=>{resolve(query.result.some(d=>d.doc.fileName==='drop.md'&&d.handle instanceof FileSystemFileHandle&&d.baseline));db.close()};query.onerror=()=>reject(query.error)}})),true);
  await page.reload();await page.getByRole('button',{name:'Continue where you left off',exact:true}).click();await page.locator('.recent-list button').filter({hasText:'drop.md'}).click();await mode('Code');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Recovered edit.');await save();assert.match(await read('drop.md'),/Recovered edit\./);assert.equal(await calls(),0);ok('Recovery persists native handles and reuses the original destination after reload');
  await page.evaluate(()=>window.__write('drop.md','Externally changed.'));await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Pending conflict.');await save();await app().getByRole('heading',{name:'This file was changed outside Termd.',exact:true}).waitFor();assert.equal(await read('drop.md'),'Externally changed.');await app().locator('.modal-heading').getByRole('button',{name:'Close',exact:true}).click();ok('File association retains conflict detection and never overwrites an external change');
  await page.getByRole('button',{name:'New document',exact:true}).click();await page.getByRole('menuitem',{name:'Commented Markdown (.trmd)',exact:true}).click();await app().locator('.ProseMirror').click();await page.keyboard.insertText('Native review document.');await page.evaluate(()=>window.__saveName='native.trmd');await save();const trmdCount=await calls();await app().locator('.ProseMirror').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Saved again.');await save();assert.equal(await calls(),trmdCount);const nativeBytes=await page.evaluate(async()=>Array.from(new Uint8Array(await (await (await window.__handle('native.trmd')).getFile()).arrayBuffer())));const nativeZip=await JSZip.loadAsync(Buffer.from(nativeBytes));assert.match(await nativeZip.file('document.md').async('string'),/Saved again\./);ok('Native TRMD is saved as a valid container and subsequent saves reuse its destination');
  await page.locator('.fullscreen-toggle').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.fullscreenElement?.classList.contains('workspace')),true);for(const selector of ['.workspace>.topbar','.document-tab-strip','.document-quick-actions','.app[data-active-document="true"] .ribbon-shell','.app[data-active-document="true"] .outline-panel'])assert.ok(await page.locator(selector).isVisible());await page.getByRole('tab',{name:'drop.md',exact:true}).click();assert.equal(await page.evaluate(()=>document.fullscreenElement?.classList.contains('workspace')),true);await page.getByRole('tab',{name:'native.trmd',exact:true}).click();await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.fullscreenElement),null);ok('Fullscreen retains tabs, quick access, ribbon and outline across document switching; Escape exits');
  const fixture=await page.evaluate(async()=>{
   const [{encodeTRMD},{anchorFor}]=await Promise.all([import('/src/files.ts'),import('/src/core.ts')]);const canvas=document.createElement('canvas');canvas.width=180;canvas.height=90;const ctx=canvas.getContext('2d');ctx.fillStyle='#2457c5';ctx.fillRect(0,0,180,90);ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText('Termd export',15,52);const image=await new Promise(resolve=>canvas.toBlob(resolve));
   const source='# Research plan\n\nA paragraph with **bold**, *italic*, ~~removed~~ and [an external link](https://example.org).\n\n> A quoted passage.\n\n3. First numbered item\n4. Second numbered item\n   - Nested bullet\n\n- [ ] Pending task\n- [x] Completed task\n\n| Item | Value |\n|:---|---:|\n| alpha | 42 |\n\n```js\nconst answer = 42;\n  console.log(answer);\n```\n\n<img src="assets/plot.png" alt="Local illustration" width="180" height="90">\n\n![Second image](assets/plot.png)\n\nSpanish: revisión, carácter, ñ.\n\n'+Array.from({length:50},(_,i)=>`## Appendix ${i+1}\n\nA detailed paragraph for pagination and selectable PDF text. ${'Evidence and methods. '.repeat(12)}\n`).join('\n');
   const comment=(body,quote,status='open')=>{const from=source.indexOf(quote);return {id:crypto.randomUUID(),body,authorLabel:'Reviewer',createdAt:'2026-10-05T09:00:00Z',updatedAt:'2026-10-05T09:00:00Z',status,anchor:anchorFor(source,from,from+quote.length),replies:[]}};
   const a=comment('Bold review','bold');a.replies=[{id:crypto.randomUUID(),body:'Reply preserved',authorLabel:'Author',createdAt:'2026-10-05T09:05:00Z'}];const b=comment('Table review','alpha','resolved'),c=comment('Unattached review','paragraph');c.anchor.state='orphan';c.anchor.quote='Previously deleted passage';c.anchor.prefix='';c.anchor.suffix='';
   return Array.from(await encodeTRMD({documentId:crypto.randomUUID(),fileName:'exports.trmd',format:'trmd',source,comments:[a,b,c],bom:false},new Map([['assets/plot.png',image]])));
  });
  await app().locator('input[type=file]').first().setInputFiles({name:'exports.trmd',mimeType:'application/octet-stream',buffer:Buffer.from(fixture)});await page.getByRole('tab',{name:'exports.trmd',selected:true,exact:true}).waitFor();await page.waitForTimeout(100);await file();const buttons=app().locator('.ribbon');for(const name of ['Print','Export PDF','Export DOCX'])assert.ok(await buttons.getByRole('button',{name,exact:true}).isVisible());assert.equal(await buttons.getByRole('button',{name:'Print / PDF',exact:true}).count(),0);ok('File has a separate Export group with Print, PDF and Word icons');
  await buttons.getByRole('button',{name:'Print',exact:true}).click();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__printCalls),1);ok('Print uses the browser print dialog and returns to the original view');
  const dir=path.resolve('../outputs/termd152-qa');await fs.mkdir(dir,{recursive:true});
  const download=async action=>{const wait=page.waitForEvent('download');await action();let item;try{item=await wait}catch(e){console.log('DOWNLOAD ERROR UI',await app().innerText());throw e}return {name:item.suggestedFilename(),bytes:await fs.readFile(await item.path())}};
  const saveBefore=await calls();await buttons.getByRole('button',{name:'Export DOCX',exact:true}).click();assert.ok(await app().getByRole('checkbox',{name:'Include comments',exact:true}).isChecked());const word=await download(()=>app().getByRole('dialog').getByRole('button',{name:'Export',exact:true}).click());assert.equal(word.name,'exports.docx');await fs.writeFile(path.join(dir,'export-with-comments.docx'),word.bytes);const archive=await JSZip.loadAsync(word.bytes),xml=await archive.file('word/document.xml').async('string');assert.match(xml,/Heading1/);assert.match(xml,/<w:b\/>/);assert.match(xml,/<w:i\/>/);assert.match(xml,/<w:strike\/>/);assert.match(xml,/<w:tbl>/);assert.match(xml,/const answer = 42;/);assert.equal(Object.keys(archive.files).filter(name=>name.startsWith('word/media/')&&!archive.files[name].dir).length,1);assert.match(await archive.file('word/_rels/document.xml.rels').async('string'),/https:\/\/example.org/);ok('DOCX contains editable text, headings, emphasis, lists, table, code, hyperlink and embedded images');
  const comments=await archive.file('word/comments.xml').async('string');assert.match(comments,/Bold review/);assert.match(comments,/Reply preserved/);assert.match(comments,/Table review/);assert.equal((xml.match(/<w:commentRangeStart /g)||[]).length,2);assert.equal((xml.match(/<w:commentRangeEnd /g)||[]).length,2);const extended=await archive.file('word/commentsExtended.xml').async('string');assert.match(extended,/paraIdParent/);assert.match(extended,/done="1"/);assert.match(xml,/Unattached review/);assert.match(xml,/<w:commentRangeStart[^>]*>[\s\S]*?alpha/);ok('Word exports anchored comments, table anchors, threaded replies, resolved state and an appendix for unattached threads');
  assert.equal(await calls(),saveBefore);assert.equal(await page.getByRole('tab',{selected:true}).getAttribute('aria-label'),'exports.trmd');await app().getByRole('heading',{name:'Export notes',exact:true}).waitFor();await app().getByRole('dialog').getByRole('button',{name:'Close',exact:true}).last().click();ok('Export creates a copy, preserves the TRMD tab/save destination and reports unattached comments');
  await buttons.getByRole('button',{name:'Export DOCX',exact:true}).click();await app().getByRole('checkbox',{name:'Include comments',exact:true}).uncheck();const clean=await download(()=>app().getByRole('dialog').getByRole('button',{name:'Export',exact:true}).click()),cleanZip=await JSZip.loadAsync(clean.bytes);assert.equal(cleanZip.file('word/comments.xml'),null);assert.ok(!(await cleanZip.file('word/document.xml').async('string')).includes('Unattached review'));await fs.writeFile(path.join(dir,'export-clean.docx'),clean.bytes);ok('Disabling Include comments produces a clean Word copy without review text');
  const pdf=await download(()=>buttons.getByRole('button',{name:'Export PDF',exact:true}).click());assert.equal(pdf.name,'exports.pdf');assert.equal(pdf.bytes.subarray(0,5).toString(),'%PDF-');await fs.writeFile(path.join(dir,'export.pdf'),pdf.bytes);assert.equal(await calls(),saveBefore);ok('Export PDF generates a real PDF directly without invoking Print or changing the save destination');
  await page.screenshot({path:path.join(dir,'file-ribbon.png')});await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('heading',{name:'No active document',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);ok('Quick access and global fullscreen control fit the mobile startup layout');
  assert.deepEqual(errors,[]);ok('No uncaught browser exceptions');console.log(JSON.stringify({passed,errors}));
 }finally{if(browser)await browser.close();server.kill()}
})().catch(error=>{console.error(error);process.exitCode=1});
