const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const fs = require('node:fs/promises'), path = require('node:path'), assert = require('node:assert/strict'), { spawn } = require('node:child_process');
(async () => {
 const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', '5183'], { stdio: 'ignore' }); let browser;
 try {
  for (let i = 0; i < 50; i++) { try { await fetch('http://127.0.0.1:5183/'); break; } catch { await new Promise(r => setTimeout(r, 100)); } }
  browser = await chromium.launch({ headless: true, args: packed.args, executablePath: process.env.WORDMD_BROWSER || path.resolve('../qa-browser/chromium') });
  const context = await browser.newContext({ viewport: { width: 1500, height: 1000 } }), page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  // Previous releases persisted preview as their automatic default.
  await page.addInitScript(() => { if (!localStorage.getItem('wordmd.settings')) localStorage.setItem('wordmd.settings', JSON.stringify({ splitMode: 'preview', recovery: false })); });
  await page.addInitScript(() => { window.showSaveFilePicker = undefined; });await page.addInitScript(() => { const saved = JSON.parse(localStorage.getItem('wordmd.settings') || '{}'); localStorage.setItem('wordmd.settings', JSON.stringify({...saved, lang: 'es'})); });await page.goto('http://127.0.0.1:5183/');await page.getByRole('button',{name:/^(Welcome document|Documento de bienvenida)$/}).click();
  const app = () => page.locator('.app[data-active-document="true"]');
  const mode = async name => { await app().locator('.status-modes').getByRole('button', { name, exact: true }).click(); await page.waitForTimeout(100); };
  const preference = async value => { await page.getByRole('button', { name: 'Configuración', exact: true }).click(); await app().getByLabel('Modo de vista dividida').selectOption(value); await app().locator('.modal-heading').getByRole('button', { name: 'Cerrar', exact: true }).click(); };
  const download = async () => { await app().locator('.tabs').getByRole('button', { name: 'Archivo', exact: true }).click(); const event = page.waitForEvent('download'); await app().locator('.ribbon').getByRole('button', { name: 'Guardar', exact: true }).click(); return fs.readFile(await (await event).path()); };
  const eventually = async fn => { let last; for (let i = 0; i < 30; i++) { try { return await fn(); } catch (e) { last = e; await page.waitForTimeout(50); } } throw last; };
  const visibleInPane = async (target, pane) => { const r = await target.boundingBox(), s = await pane.boundingBox(); assert.ok(r && s && r.y >= s.y - 5 && r.y + r.height <= s.y + s.height + 5, JSON.stringify({ r, s })); };
  const noGlobalScroll = async () => assert.deepEqual(await app().locator('.canvas').evaluate(el => ({ canvas: el.scrollTop, body: document.scrollingElement.scrollTop })), { canvas: 0, body: 0 });
  let passed = 0; const ok = name => { passed++; console.log('PASS ' + name); };
  await mode('Dividido'); await app().locator('.ProseMirror').waitFor(); assert.ok(await app().locator('.ProseMirror').isVisible());
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('wordmd.settings')).splitMode), 'editable'); ok('Editable split is the default, including migration from the old default');
  await preference('preview'); assert.ok(await app().locator('.reading').isVisible()); await page.reload(); await page.getByRole('button',{name:'Documento de bienvenida',exact:true}).click(); await mode('Dividido'); assert.ok(await app().locator('.reading').isVisible()); ok('Explicit reading preference remains available and persists after reload');
  await preference('editable');
  const source = Array.from({ length: 120 }, (_, i) => `## Sección ${i + 1} 🧭\r\n\r\nPárrafo ${i + 1}. Un **texto** con acentos, &amp; y un [enlace](https://example.com). ${'Contenido que permite comprobar el desplazamiento. '.repeat(3)}`).join('\r\n\r\n');
  await app().locator('input[type=file]').first().setInputFiles({ name: 'scroll.md', mimeType: 'text/markdown', buffer: Buffer.from('\uFEFF' + source) }); await page.getByRole('tab', { name: 'scroll.md', exact: true }).waitFor(); await mode('Dividido');
  const visual = () => app().locator('.visual-scroll'), code = () => app().locator('.cm-scroller');
  const layout = await app().evaluate(el => { const canvas = el.querySelector('.canvas'), c = el.querySelector('.cm-scroller'), v = el.querySelector('.visual-scroll'); return { canvasHeight: canvas.clientHeight, canvasContent: canvas.scrollHeight, code: [c.clientHeight, c.scrollHeight], visual: [v.clientHeight, v.scrollHeight], overflow: getComputedStyle(canvas).overflowY }; });
  assert.equal(layout.overflow, 'hidden'); assert.ok(layout.canvasContent <= layout.canvasHeight + 1, JSON.stringify(layout)); assert.ok(layout.code[1] > layout.code[0] && layout.visual[1] > layout.visual[0]); ok('Split fills the workspace and exposes two independent vertical scrollers');
  await visual().evaluate(el => el.scrollTop = 2500); await code().evaluate(el => el.scrollTop = 0); const vb = await visual().boundingBox(); await page.mouse.move(vb.x + 100, vb.y + 100); await page.mouse.wheel(0, 600); await page.waitForTimeout(150); assert.equal(await code().evaluate(el => el.scrollTop), 0); await noGlobalScroll(); ok('Visual scrolling stays in its pane and leaves code and workspace fixed');
  const visualTop = await visual().evaluate(el => el.scrollTop); const cb = await code().boundingBox(); await page.mouse.move(cb.x + 100, cb.y + 100); await page.mouse.wheel(0, 650); await page.waitForTimeout(150); assert.ok(await code().evaluate(el => el.scrollTop) > 0); assert.equal(await visual().evaluate(el => el.scrollTop), visualTop); await noGlobalScroll(); ok('Code scrolling leaves visual at its independent position');
  const canvasBox = await app().locator('.canvas').boundingBox(); await page.mouse.move(canvasBox.x + 5, canvasBox.y + 5); await page.mouse.wheel(0, 1000); await page.waitForTimeout(120); await noGlobalScroll(); ok('Scrolling the workspace background cannot hide either pane');
  await code().evaluate(el => el.scrollTop = el.scrollHeight * .65); await page.waitForTimeout(150);
  const headingLine = await app().locator('.cm-line').evaluateAll(lines => { const pane = lines[0].closest('.cm-scroller').getBoundingClientRect(); return lines.filter(el => /## Sección \d+/.test(el.textContent)).map(el => ({ text: el.textContent, r: el.getBoundingClientRect() })).find(x => x.r.top > pane.top + 60 && x.r.bottom < pane.bottom - 40)?.text; }); assert.ok(headingLine);
  const section = Number(headingLine.match(/Sección (\d+)/)[1]); await app().locator('.cm-line').filter({ hasText: headingLine }).click({ position: { x: 100, y: 12 } });
  await eventually(() => visibleInPane(app().locator('.ProseMirror h2').filter({ hasText: `Sección ${section} 🧭` }), visual())); assert.ok(await app().locator('.cm-content').evaluate(el => el.contains(document.activeElement))); await noGlobalScroll(); ok('Clicking a virtualized code line scrolls visual to its exact section without stealing focus');
  // Repeat at the same cursor position after independently moving the other pane.
  await visual().evaluate(el => el.scrollTop = 0); await app().locator('.cm-line').filter({ hasText: headingLine }).click({ position: { x: 100, y: 12 } }); await eventually(() => visibleInPane(app().locator('.ProseMirror h2').filter({ hasText: `Sección ${section} 🧭` }), visual())); ok('Clicking the same code position resynchronizes a separately scrolled visual pane');
  const target = app().locator('.ProseMirror h2').filter({ hasText: 'Sección 9 🧭' }); await target.evaluate(el => { const s = el.closest('.visual-scroll'); s.scrollTop += el.getBoundingClientRect().top - s.getBoundingClientRect().top - s.clientHeight / 2; }); await target.click();; await eventually(async () => { const line = app().locator('.cm-line').filter({ hasText: '## Sección 9 🧭' }); assert.equal(await line.count(), 1); await visibleInPane(line, code()); }); assert.ok(await app().locator('.ProseMirror').evaluate(el => el.contains(document.activeElement))); await noGlobalScroll(); ok('Clicking visual scrolls code to the matching UTF-16 and CRLF position and preserves visual focus');
  await code().evaluate(el => el.scrollTop = el.scrollHeight * .7); await target.click(); await eventually(() => visibleInPane(app().locator('.cm-line').filter({ hasText: '## Sección 9 🧭' }), code())); ok('Repeated visual clicks also restore the corresponding code position');
  await app().locator('.cm-content').click(); await page.keyboard.press('Control+Home'); await page.evaluate(() => window.keptHeading = document.querySelector('.app[data-active-document="true"] .ProseMirror h2:last-of-type')); await page.keyboard.insertText('Introducción.\n\n');
  assert.equal(await app().locator('.ProseMirror p').first().textContent(), 'Introducción.'); assert.equal(await page.evaluate(() => window.keptHeading === document.querySelector('.app[data-active-document="true"] .ProseMirror h2:last-of-type')), true); assert.deepEqual(await download(), Buffer.from('\uFEFFIntroducción.\r\n\r\n' + source)); ok('Incremental code update retains unrelated visual DOM, BOM and CRLF byte for byte');
  await app().locator('.ProseMirror p').first().click(); await page.keyboard.press('End'); await page.keyboard.insertText(' Añadido'); assert.deepEqual(await download(), Buffer.from('\uFEFFIntroducción. Añadido\r\n\r\n' + source)); await page.keyboard.press('Control+z'); assert.deepEqual(await download(), Buffer.from('\uFEFFIntroducción.\r\n\r\n' + source)); await page.keyboard.press('Control+z'); assert.deepEqual(await download(), Buffer.from('\uFEFF' + source)); ok('Visual updates reuse unchanged AST offsets; shared undo restores exact source');
  await mode('Código'); await noGlobalScroll(); assert.ok((await code().boundingBox()).height > 200); await app().locator('.tabs').getByRole('button', { name: 'Vista', exact: true }).click(); await app().locator('.ribbon').getByRole('button', { name: 'Pantalla completa', exact: true }).click(); await noGlobalScroll(); const focusHeight = (await code().boundingBox()).height; assert.ok(focusHeight > layout.code[0]); await app().locator('.exit-fullscreen').click(); ok('Code-only and focus layouts keep the editor inside a fixed workspace');
  await mode('Dividido'); await page.setViewportSize({ width: 720, height: 700 }); await page.waitForTimeout(100); await noGlobalScroll(); assert.ok((await code().boundingBox()).height < 700); assert.ok((await visual().boundingBox()).height < 700); ok('Small screens retain pane height and horizontal access without nested vertical workspace scroll');
  await page.setViewportSize({ width: 1500, height: 1000 }); await page.screenshot({ path: '../outputs/termd-split-scroll.png' });
  assert.deepEqual(errors, []); ok('No uncaught browser exceptions'); console.log(JSON.stringify({ passed, errors }, null, 2));
 } finally { if (browser) await browser.close(); server.kill(); }
})().catch(e => { console.error(e); process.exit(1); });
