const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const assert = require('node:assert/strict'), fs = require('node:fs/promises'), path = require('node:path'), { spawn } = require('node:child_process');
(async () => {
 const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', '5184'], { stdio: 'ignore' }); let browser;
 try {
  for (let i = 0; i < 50; i++) { try { await fetch('http://127.0.0.1:5184/'); break; } catch { await new Promise(r => setTimeout(r, 100)); } }
  browser = await chromium.launch({ headless: true, args: packed.args, executablePath: process.env.WORDMD_BROWSER || path.resolve('../qa-browser/chromium') });
  const context = await browser.newContext({ viewport: { width: 1500, height: 1000 } }), page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message)); await page.addInitScript(() => localStorage.setItem('wordmd.settings', JSON.stringify({ recovery: false })));
  await page.addInitScript(() => { window.showSaveFilePicker = undefined; });await page.addInitScript(() => { const saved = JSON.parse(localStorage.getItem('wordmd.settings') || '{}'); localStorage.setItem('wordmd.settings', JSON.stringify({...saved, lang: 'es'})); });await page.goto('http://127.0.0.1:5184/');await page.getByRole('button',{name:/^(Welcome document|Documento de bienvenida)$/}).click(); await page.locator('.ProseMirror').waitFor();
  const app = () => page.locator('.app[data-active-document="true"]:visible'), nav = () => app().locator('.tabs'), ribbon = () => app().locator('.ribbon');
  const tab = name => nav().getByRole('button', { name, exact: true }), tableTab = () => tab('Tabla');
  const source = '# Tabla contextual\n\nAntes de la tabla.\n\n| A | B |\n| --- | --- |\n| Uno | Dos |\n\nDespués de la tabla.\n';
  await app().locator('input[type=file]').first().setInputFiles({ name: 'table.md', mimeType: 'text/markdown', buffer: Buffer.from(source) }); await page.getByRole('tab', { name: 'table.md', exact: true }).waitFor();
  const cell = () => app().locator('.ProseMirror td').first();
  const clickCell = async () => { await cell().click(); await tableTab().waitFor(); };
  const mode = async name => { await app().locator('.status-modes').getByRole('button', { name, exact: true }).click(); };
  const waitFor = async fn => { let last; for (let i = 0; i < 30; i++) { try { return await fn(); } catch (e) { last = e; await page.waitForTimeout(40); } } throw last; };
  const download = async () => { await tab('Archivo').click(); const event = page.waitForEvent('download'); await ribbon().getByRole('button', { name: 'Guardar', exact: true }).click(); return (await fs.readFile(await (await event).path())).toString(); };
  let passed = 0; const ok = name => { passed++; console.log('PASS ' + name); };
  await app().locator('.ProseMirror h1').filter({hasText:'Tabla contextual'}).waitFor(); assert.equal(await tableTab().count(), 0); const height = await app().locator('.canvas').evaluate(el => el.clientHeight); ok('Table tab is absent while the cursor is outside the table');
  await clickCell(); assert.equal(await tab('Inicio').getAttribute('class'), 'active'); assert.notEqual(await tableTab().getAttribute('class'), 'active'); assert.deepEqual(await nav().locator('button').allTextContents(), ['Archivo', 'Inicio', 'Insertar', 'Revisar', 'Vista', 'Tabla']); assert.equal(await app().locator('.table-context').count(), 0); assert.equal(await app().locator('.canvas').evaluate(el => el.clientHeight), height); ok('Clicking a table reveals Tabla after Vista, keeps Inicio active and preserves workspace height');
  for (const name of ['Archivo', 'Inicio', 'Insertar', 'Revisar', 'Vista']) { await tab(name).click(); await app().locator('.ProseMirror > p').last().click(); const labels=await ribbon().locator('button').allTextContents(), before=await ribbon().boundingBox(); await clickCell(); assert.equal(await tab(name).getAttribute('class'),'active'); assert.deepEqual(await ribbon().locator('button').allTextContents(),labels); const after=await ribbon().boundingBox(); assert.equal(after.y,before.y); assert.equal(after.height,before.height); } ok('Every normal tab and its ribbon remain unchanged when entering a table');
  await tableTab().click();
  for (const name of ['Añadir fila', 'Añadir columna', 'Eliminar fila', 'Eliminar columna', 'Eliminar tabla', 'Alineación de columna: Izquierda', 'Alineación de columna: Centro', 'Alineación de columna: Derecha', 'Salir de la tabla']) assert.ok(await ribbon().getByRole('button', { name, exact: true }).isVisible()); ok('All existing table tools appear in the normal ribbon');
  await tab('Inicio').click(); assert.ok(await tableTab().isVisible()); assert.ok(await ribbon().getByRole('button', { name: 'Negrita', exact: true }).isVisible()); await tableTab().click(); await ribbon().getByRole('button', { name: 'Añadir fila', exact: true }).click(); assert.equal(await app().locator('.ProseMirror tr').count(), 3); await ribbon().getByRole('button', { name: 'Añadir columna', exact: true }).click(); assert.equal(await app().locator('.ProseMirror tr').first().locator('th').count(), 3); ok('Other tabs remain usable and table controls preserve the cell selection');
  await ribbon().getByRole('button', { name: 'Alineación de columna: Derecha', exact: true }).click(); assert.ok((await download()).includes('---:')); await tableTab().click(); await ribbon().getByRole('button', { name: 'Eliminar columna', exact: true }).click(); assert.equal(await app().locator('.ProseMirror th').count(), 2); await ribbon().getByRole('button', { name: 'Eliminar fila', exact: true }).click(); assert.equal(await app().locator('.ProseMirror tr').count(), 2); ok('Column alignment and row/column deletion still work from Tabla');
  await ribbon().getByRole('button', { name: 'Salir de la tabla', exact: true }).click(); await tableTab().waitFor({ state: 'detached' }); assert.ok((await nav().locator('button.active').textContent()).trim()); assert.ok(await ribbon().locator('button').count() > 0); ok('Exit table hides Tabla and restores a populated normal ribbon');
  await tab('Vista').click(); await clickCell(); await app().locator('.ProseMirror > p').last().click(); await tableTab().waitFor({ state: 'detached' }); assert.equal(await tab('Vista').getAttribute('class'), 'active'); ok('Clicking a paragraph restores the previously selected Vista tab');
  await clickCell(); await tableTab().click(); await ribbon().getByRole('button', { name: 'Eliminar tabla', exact: true }).click(); await tableTab().waitFor({ state: 'detached' }); assert.equal(await app().locator('.ProseMirror table').count(), 0); await page.keyboard.press('Control+z'); assert.equal(await app().locator('.ProseMirror table').count(), 1); await clickCell(); ok('Deleting a table removes the contextual tab; undo restores the table and its tools');
  await mode('Dividido'); await app().locator('.cm-content').waitFor(); await clickCell(); await app().locator('.cm-content').click(); await tableTab().waitFor({ state: 'detached' }); await clickCell(); await tableTab().click(); await ribbon().getByRole('button', { name: 'Añadir columna', exact: true }).click(); assert.ok((await app().locator('.cm-content').innerText()).includes('|')); assert.equal(await app().locator('.ProseMirror th').count(), 3); ok('Editable split shows Tabla for visual editing, hides it on source focus and synchronizes table edits');
  await mode('Lectura'); await app().locator('.reading').waitFor(); await app().locator('.reading td').first().click(); assert.equal(await tableTab().count(), 0); await mode('Código'); await app().locator('.cm-content').waitFor(); assert.equal(await tableTab().count(), 0); ok('Reading and code-only views do not expose visual table tools');
  await mode('Visual'); await clickCell(); await tableTab().click(); await page.getByRole('button', { name: 'Configuración', exact: true }).click(); await app().locator('.settings-modal select').first().selectOption('en'); await app().locator('.modal-heading').getByRole('button', { name: 'Close', exact: true }).click(); await cell().click(); await nav().getByRole('button', { name: 'Table', exact: true }).waitFor(); assert.deepEqual(await nav().locator('button').allTextContents(), ['File', 'Home', 'Insert', 'Review', 'View', 'Table']); await nav().getByRole('button', { name: 'Table', exact: true }).click(); assert.ok(await ribbon().getByRole('button', { name: 'Add row', exact: true }).isVisible()); ok('The contextual Table tab and tools retain English support');
  await page.getByRole('button', {name:'New document',exact:true}).click(); await page.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).click(); await app().locator('.ProseMirror').waitFor(); assert.equal(await nav().getByRole('button',{name:'Table',exact:true}).count(),0); await page.getByRole('tab',{name:'table.md',exact:true}).click(); await cell().click(); await nav().getByRole('button',{name:'Table',exact:true}).waitFor(); ok('Table ribbon belongs to the active document and resumes after switching tabs');
  for (const name of ['Visual', 'Reading', 'Split']) { await mode(name); await app().locator('.visual-scroll').waitFor(); assert.equal(await app().locator('.paper-caption').count(),0); }
  await waitFor(async () => {const paper=await app().locator('.paper-wrap').boundingBox(),editor=await app().locator('.visual-scroll').boundingBox(); assert.ok(Math.abs(paper.y+paper.height-editor.y-editor.height)<2)}); ok('The Markdown caption is removed from visual, reading and split views; split editor fills the bottom space');
  await mode('Visual'); await cell().click(); await nav().getByRole('button',{name:'Table',exact:true}).waitFor();
  await page.setViewportSize({ width: 720, height: 700 }); const table = nav().getByRole('button', { name: 'Table', exact: true }); await table.click(); assert.ok(await table.isVisible()); const deleteButton = ribbon().getByRole('button', { name: 'Delete table', exact: true }); await deleteButton.scrollIntoViewIfNeeded(); assert.ok(await deleteButton.isVisible()); await page.setViewportSize({ width: 1500, height: 1000 }); await page.screenshot({ path: '../outputs/termd-table-ribbon.png' }); ok('Narrow screens can reach the tab and scroll to all table tools');
  assert.deepEqual(errors, []); ok('No uncaught browser exceptions'); console.log(JSON.stringify({ passed, errors }, null, 2));
 } finally { if (browser) await browser.close(); server.kill(); }
})().catch(e => { console.error(e); process.exit(1); });
