const { chromium } = require('playwright-core'), packed = require('@sparticuz/chromium').default;
const fs = require('node:fs/promises'), path = require('node:path'), assert = require('node:assert/strict'), { spawn } = require('node:child_process'), JSZip = require('jszip');
(async()=>{
 const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5180'],{stdio:'ignore'});let browser;
 try {
  for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:5180/');break}catch{await new Promise(r=>setTimeout(r,120))}}
  browser=await chromium.launch({headless:true,args:packed.args,executablePath:process.env.WORDMD_BROWSER||path.resolve('../qa-browser/chromium')});
  const context=await browser.newContext({viewport:{width:1500,height:1000}}), page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.addInitScript(() => { window.showSaveFilePicker = undefined; if (!localStorage.getItem('wordmd.settings')) localStorage.setItem('wordmd.settings', JSON.stringify({lang: 'es'})); });await page.goto('http://127.0.0.1:5180/');
  const app=()=>page.locator('.app[data-active-document="true"]'), tab=name=>page.getByRole('tab',{name,exact:true});
  const open=async(source,name)=>{await app().locator('input[type=file]').first().setInputFiles({name,mimeType:'text/markdown',buffer:Buffer.from(source)});await tab(name).waitFor();await app().locator('.ProseMirror,.cm-content').first().waitFor()};
  const mode=async(name)=>{await app().locator('.status-modes').getByRole('button',{name,exact:true}).click();await page.waitForTimeout(50)};
  const download=async()=>{await app().locator('.tabs').getByRole('button',{name:'Archivo',exact:true}).click();const wait=page.waitForEvent('download');await app().locator('.ribbon').getByRole('button',{name: (await page.getByRole('tab',{selected:true}).getAttribute('aria-label')).endsWith('.trmd')?'Guardar .md…':'Guardar',exact:true}).click();return fs.readFile(await (await wait).path())};
  const select=async(text)=>{await app().locator('.ProseMirror').evaluate((el,text)=>{el.focus();const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const i=n.textContent.indexOf(text);if(i>=0){let r=document.createRange();r.setStart(n,i);r.setEnd(n,i+text.length);getSelection().removeAllRanges();getSelection().addRange(r);return}}throw Error(text)},text);await page.waitForTimeout(70)};
  let passed=0;const ok=n=>{passed++;console.log('PASS '+n)};
  assert.equal(await page.locator('.brand strong').textContent(),'Termd');assert.ok((await page.title()).startsWith('Termd'));assert.ok(await page.locator('.app-icon').isVisible());ok('Termd name and rounded SVG logo');
  await open('# Sync\n\nAlpha text.\n','one.md');await open('\uFEFF# Two\r\n\r\nSecond exact.','two.md');assert.equal(await page.getByRole('tab').count(),3);await tab('one.md').click();assert.equal((await download()).toString(),'# Sync\n\nAlpha text.\n');assert.equal(await page.getByRole('dialog').count(),0);ok('Opening adds independent tabs; ordinary clicks select without rename');
  await mode('Dividido');assert.ok(await app().locator('.ProseMirror').isVisible());assert.ok(await app().locator('.cm-content').isVisible());ok('Default split enables code and editable visual');
  await page.getByRole('button',{name:'Configuración',exact:true}).click();await app().getByLabel('Modo de vista dividida').selectOption('preview');await app().locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();assert.ok(await app().locator('.reading').isVisible());assert.equal(await app().locator('.ProseMirror').count(),0);ok('Reading split remains an optional preference');
  await page.getByRole('button',{name:'Configuración',exact:true}).click();await app().getByLabel('Modo de vista dividida').selectOption('editable');await app().locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();assert.ok(await app().locator('.ProseMirror').isVisible());assert.ok(await app().locator('.cm-content').isVisible());ok('General settings enables editable split immediately');
  await app().locator('.cm-content').click();await page.keyboard.press('Control+Home');await page.keyboard.insertText('Intro.\n\n');assert.equal(await app().locator('.ProseMirror p').first().textContent(),'Intro.');ok('Code edits synchronize into the visual pane');
  await app().locator('.ProseMirror p').last().click();await page.keyboard.press('End');await page.keyboard.insertText(' Visual');assert.ok((await app().locator('.cm-content').innerText()).includes('Alpha text. Visual'));ok('Visual edits synchronize into source');
  await page.waitForTimeout(700);await select('Alpha');await app().locator('.tabs').getByRole('button',{name:'Inicio',exact:true}).click();await app().locator('.ribbon').getByRole('button',{name:'Negrita',exact:true}).click();assert.ok((await app().locator('.cm-content').innerText()).includes('**Alpha**'));await app().locator('.cm-content').click();await page.keyboard.press('Control+z');assert.ok(!(await app().locator('.cm-content').innerText()).includes('**Alpha**'));await page.keyboard.press('Control+Shift+z');assert.ok((await app().locator('.cm-content').innerText()).includes('**Alpha**'));ok('Split formatting targets focused pane; common undo and redo');
  const first=(await download()).toString();await tab('two.md').click();assert.deepEqual(await download(),Buffer.from('\uFEFF# Two\r\n\r\nSecond exact.'));await mode('Código');await app().locator('.cm-content').click();await page.keyboard.press('Control+End');await page.keyboard.insertText(' Edited');await tab('one.md').click();assert.equal((await download()).toString(),first);await tab('two.md').click();await page.keyboard.press('Control+z');assert.deepEqual(await download(),Buffer.from('\uFEFF# Two\r\n\r\nSecond exact.'));ok('Each tab preserves text, BOM/CRLF, mode and independent undo history');
  await tab('one.md').click();const box=await tab('one.md').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up();await page.getByLabel('Nombre del documento').fill('renamed');await page.getByLabel('Nombre del documento').press('Enter');await tab('renamed.md').waitFor();assert.equal(await page.getByRole('dialog').count(),0);ok('Holding the name renames inline without a modal');
  await tab('renamed.md').click({button:'right'});await page.getByRole('menuitem',{name:'Cambiar nombre',exact:true}).click();await page.getByLabel('Nombre del documento').fill('cancelled');await page.getByLabel('Nombre del documento').press('Escape');await tab('renamed.md').waitFor();ok('Context menu rename and Escape cancellation');
  await page.getByRole('button',{name:'Cerrar renamed.md',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Cancelar',exact:true}).click();await tab('renamed.md').waitFor();ok('X warns for modified text or names; cancel preserves the tab');
  await page.evaluate(()=>window.showSaveFilePicker=undefined);await tab('two.md').click({button:'right'});const wait=page.waitForEvent('download');await page.getByRole('menuitem',{name:'Guardar',exact:true}).click();const saved=await wait;assert.equal(saved.suggestedFilename(),'two.md');assert.deepEqual(await fs.readFile(await saved.path()),Buffer.from('\uFEFF# Two\r\n\r\nSecond exact.'));ok('Context save targets the clicked background document');
  await tab('renamed.md').click();await mode('Dividido');await select('Alpha');await page.keyboard.press('Control+Alt+m');const convertWait=page.waitForEvent('download');await app().locator('.modal').getByRole('button',{name:'Guardar como .trmd…',exact:true}).click();await convertWait;await app().locator('#new-comment-text').fill('Pending review kept on close');await page.getByRole('button',{name:'Cerrar renamed.trmd',exact:true}).click();const archiveWait=page.waitForEvent('download');await page.getByRole('button',{name:'Guardar y cerrar',exact:true}).click();const archive=await JSZip.loadAsync(await fs.readFile(await (await archiveWait).path()));const comments=JSON.parse(await archive.file('comments.json').async('string'));assert.equal(comments.comments[0].body,'Pending review kept on close');assert.equal(comments.comments[0].anchor.quote,'Alpha');await tab('renamed.trmd').waitFor({state:'detached'});ok('Save and close includes an unfinished comment draft and Markdown');
  await tab('two.md').click({button:'right'});await page.getByRole('menuitem',{name:'Cerrar',exact:true}).click();await tab('two.md').waitFor({state:'detached'});assert.equal(await page.getByRole('dialog').count(),0);ok('Context close removes a saved document without warning');
  await page.getByRole('button',{name:'Ayuda',exact:true}).click();assert.equal(await app().locator('.help-content section').count(),7);assert.ok(await app().locator('.help-table').isVisible());await page.screenshot({path:'../outputs/wordmd-qa/termd-help.png'});await app().locator('.modal-heading').getByRole('button',{name:'Cerrar',exact:true}).click();ok('Expanded help has sections, navigation, save table and shortcuts');
  await page.getByRole('button',{name:'Nuevo documento',exact:true}).click();await page.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).click();await mode('Dividido');assert.ok(await app().locator('.ProseMirror').isVisible());await page.screenshot({path:'../outputs/wordmd-qa/termd-split.png'});ok('Shared split preference applies to new documents');
  await app().locator('.cm-content').click();await page.keyboard.insertText('Keep this unsaved.');await page.getByRole('button',{name:'Nuevo documento',exact:true}).click();await page.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).click();await page.waitForTimeout(100);await page.reload();await page.getByRole('heading',{name:'Continuar donde lo dejaste',exact:true}).waitFor();assert.ok((await app().locator('.recent-list').innerText()).includes('Documento 1.md'));ok('Fast switching flushes recovery copies for inactive documents');
  assert.deepEqual(errors,[]);ok('No uncaught browser exceptions');console.log(JSON.stringify({passed,errors},null,2));
 }finally{if(browser)await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exit(1)});
